// Writes src/app/lib/crypto/fixtures/go-ibax-vectors.json: for every cryptoer and hasher go-ibax
// implements, and a few private keys, the public key, the account id and a signature of a login
// message as go-ibax computes them (packages/common/crypto). go-ibax's own P256.Sign panics on
// Go >= 1.20 (it leaves the public point unset), so P-256 signatures are made with crypto/ecdsa
// over the same hash; every signature is checked with go-ibax's crypto.Verify before it is written.
//
// Run from a Go module that requires github.com/IBAX-io/go-ibax (at 66f1358) and
// github.com/tjfoc/gmsm v1.4.1:  go run . > go-ibax-vectors.json
package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"math/big"
	"os"
	"strconv"

	"github.com/IBAX-io/go-ibax/packages/common/crypto"
	"github.com/IBAX-io/go-ibax/packages/conf"
)

type Vector struct {
	Cryptoer    string  `json:"cryptoer"`
	Hasher      string  `json:"hasher"`
	PrivateKey  string  `json:"privateKey"`
	PublicKey   string  `json:"publicKey"`
	KeyID       string  `json:"keyID"`
	Message     string  `json:"message"`
	GoSignature *string `json:"goSignature"`
	Payload     string  `json:"payload"`
}

var keys = []string{
	"e5a87a96a445cb55a214edaad3661018061ef2936e63a0a93bdb76eb28251c1f",
	"0000000000000000000000000000000000000000000000000000000000000001",
	"a1b2c3d4e5f60718293a4b5c6d7e8f90112233445566778899aabbccddeeff00",
}

const message = "LOGIN58551740666882655616"
const payload = "83a6486561646572010203fafb"

func sign(cryptoer string, priv []byte, msg []byte) []byte {
	if cryptoer != "ECC_P256" {
		sig, err := crypto.Sign(priv, msg)
		if err != nil {
			panic(err)
		}
		return sig
	}
	key := new(ecdsa.PrivateKey)
	key.Curve = elliptic.P256()
	key.D = new(big.Int).SetBytes(priv)
	key.PublicKey.X, key.PublicKey.Y = key.Curve.ScalarBaseMult(priv)
	r, s, err := ecdsa.Sign(rand.Reader, key, crypto.Hash(msg))
	if err != nil {
		panic(err)
	}
	return append(r.FillBytes(make([]byte, 32)), s.FillBytes(make([]byte, 32))...)
}

func main() {
	var vectors []Vector
	for _, cryptoer := range []string{"ECC_Secp256k1", "ECC_P256", "SM2"} {
		for _, hasher := range []string{"SHA256", "KECCAK256", "SHA3_256", "SM3"} {
			conf.Config.CryptoSettings.Cryptoer = cryptoer
			conf.Config.CryptoSettings.Hasher = hasher
			crypto.InitAsymAlgo(cryptoer)
			crypto.InitHashAlgo(hasher)
			for _, k := range keys {
				priv, _ := hex.DecodeString(k)
				pub, err := crypto.PrivateToPublic(priv)
				if err != nil {
					panic(err)
				}
				sig := sign(cryptoer, priv, []byte(message))
				if ok, err := crypto.Verify(pub, []byte(message), sig); !ok || err != nil {
					panic("go-ibax refuses its own signature: " + cryptoer + "/" + hasher)
				}
				hexSig := hex.EncodeToString(sig)
				vectors = append(vectors, Vector{
					Cryptoer: cryptoer, Hasher: hasher, PrivateKey: k,
					PublicKey: "04" + hex.EncodeToString(pub), KeyID: strconv.FormatInt(crypto.Address(pub), 10),
					Message: message, GoSignature: &hexSig, Payload: payload,
				})
			}
		}
	}
	out := map[string]interface{}{
		"source":  "Generated by scripts/go-ibax-vectors/main.go with go-ibax packages/common/crypto (github.com/IBAX-io/go-ibax @66f1358, SM2 via tjfoc/gmsm v1.4.1): PrivateToPublic, Address, and a signature of the message that crypto.Verify accepts, for every cryptoer and hasher go-ibax implements (P-256 signed with crypto/ecdsa: go-ibax's P256.Sign panics on Go >= 1.20).",
		"vectors": vectors,
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(out); err != nil {
		panic(err)
	}
}
